# Stage 1: Build the React application
FROM node:lts-alpine as builder

WORKDIR /app

# Increase memory for Node.js
ENV NODE_OPTIONS=--max-old-space-size=8192

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
